### ISSUE TITLE
how to support mutable pages ?

### ISSUE THREAD

**Issue by lichanghong** [DeveloperLx/LxGridView#3]
Hello,I'm iOS developer, and I use the view do the same things as you do,but ,I don't know how to support multipage. I'm trying to use LxGridView inside a horizontal  ColloctionView,but failed. I'm using UIScreenEdgePanGestureRecognizer to transform pages. do you have any ideas? thinks.

**Comment by DeveloperLx** [comment]
You can try embed it in a horizontal scrollView~
